language: go

sudo: false

matrix:
  include:
  - go: 1.5

script:
  - GOARCH=amd64 GOOS=linux go build tmplt.go && mv tmplt tmplt_linux_64 && tar czvf tmplt-0.1.0-linux_amd64.tgz tmplt_linux_64
  - GOARCH=amd64 GOOS=darwin go build tmplt.go && mv tmplt tmplt_darwin_64 && tar czvf tmplt-0.1.0-darwin_amd64.tgz tmplt_darwin_64

  - GOARCH=386 GOOS=linux go build tmplt.go && mv tmplt tmplt_linux_32 && tar czvf tmplt-0.1.0-linux_386.tgz tmplt_linux_32
  - GOARCH=386 GOOS=darwin go build tmplt.go && mv tmplt tmplt_darwin_32 && tar czvf tmplt-0.1.0-darwin_386.tgz tmplt_darwin_32

deploy:
  provider: releases
  skip_cleanup: true

  api_key:
    secure: W2mjI9R3ZnB7QsYuJitwT/h+7jR/Pj6WSjKERLerRPN0z5nbCCJdTkw7r9gsGBblT2AMHx7qxws2S5AMS4MypJNmOj0ZW5TWiDkobAOENUbjGEjxii2yLuNxcsBE5Ets1s5dPB/RpvHh/PGTC5IX80ISVosRVTQ+ABexuLsFWcG/CpmV/Tb1BxWso3kP2UvupF3XwDJoM2a/hNQXvyzZoO7FVLD/YiWvRNPf9zqrDow3wRAg3YLHqIaHJ2V68rqXb+x/FQ4YpD21tBAAIJc1NSttOXQ3xEyhTMQP0Ba2z+FOvYBVxVJgrBZiV7B6F26GjLHBb104sLTprF6xVQKN6AcPLzgBMO6jZ2apr+On0nglMl4nRbE7TRdEzCZbEzHGxbxAhCdArObuVQN09+MNnUYtJDv/xzkwEpK1NbG/3sEL8zKhJrEYznNWCONKTHgXWp7o8pljOcV4A8nDVKVjul5/VMaZ5Swgs0BQ6QeU+EaprWP6hGuccGLUH+ZX8Wqnl7hV+rRzYIYEeR8d1df3pMUGmnWLJsbI+0K/OcAbqMCmEUBM15XX6+yaHrP1RZQTOKH8F2NR+oVl9EHEQZCt3J4DlSVzB86vkMvXgFuWXq6Q3uJSyUiOnRhGJdykHXNwdvIlkmidyVLIeKTdfCW+I4HoTHBi1/zvmm5sD1Idt2o=

  file: tmplt-0.1.0-darwin_386.tgz
  file: tmplt-0.1.0-darwin_amd64.tgz
  file: tmplt-0.1.0-linux_386.tgz
  file: tmplt-0.1.0-linux_amd64.tgz

  on:
    tags: true
