language: go

sudo: false

matrix:
  include:
  - go: 1.5

script:
  - GOARCH=amd64 GOOS=linux go build boilr.go && mv boilr boilr_linux_64 && tar czvf boilr-0.1.0-linux_amd64.tgz boilr_linux_64
  - GOARCH=amd64 GOOS=darwin go build boilr.go && mv boilr boilr_darwin_64 && tar czvf boilr-0.1.0-darwin_amd64.tgz boilr_darwin_64

  - GOARCH=386 GOOS=linux go build boilr.go && mv boilr boilr_linux_32 && tar czvf boilr-0.1.0-linux_386.tgz boilr_linux_32
  - GOARCH=386 GOOS=darwin go build boilr.go && mv boilr boilr_darwin_32 && tar czvf boilr-0.1.0-darwin_386.tgz boilr_darwin_32
